### ISSUE TITLE
Getting JS error while trying to install application on Windows

### ISSUE THREAD

**Issue by ghost** [p2pderivatives/p2pderivatives-client#105]
Screenshot of the error:

![image](https://user-images.githubusercontent.com/13405205/89292204-9bb5ef00-d679-11ea-9582-d8b964f588e0.png)

Will have to try on Linux next and I am not sure what is this error about.

**Comment by Tibo-lg** [comment]
Thanks for reporting this. Could you let us know which version of windows you are using?  

Also,  could you check if the file it is looking for is actually present (`%localappdata%\Programs\p2pdertivatives-client\ressources\app.asar.unpacked\node_modules\cfd-dlc-js\build\release\cfddlc_js.node`)?

**Comment by Tibo-lg** [comment]
@prayank23 could you try to install the VC++ redistributable (https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)? After discussing we think that is maybe your issue. Please let me know if that solves it or not. We might be able to add it as part of the windows installation process in future releases.

**Comment by ghost** [comment]
> @prayank23 could you try to install the VC++ redistributable (https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)? After discussing we think that is maybe your issue. Please let me know if that solves it or not. We might be able to add it as part of the windows installation process in future releases.

This resolved the issue. Its working now. Thanks
